version: '3'

services:
  core:
    image: brod55/wok:2.5.0
    environment:
      - USERNAME: "wok-admin"
      - HASHPASS: "$6$Ebs1dF5aSem0wDys$DlYe0a/hKW3hD7rNb/LkI2irbIBhgckLnrGICCHUWrB3DiJyvXENhfMB8wLD1EJGg3MWO3w6uWEqNAuitVJPx0"
    ipc: host
    network_mode: host
    pid: host
    privileged: true
    restart: always
    userns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/lib/wok:/var/lib/wok
      - /var/lib/kimchi:/var/lib/kimchi
      - /var/lib/gingerbase:/var/lib/gingerbase
      - /var/lib/libvirt:/var/lib/libvirt
      - /etc/libvirt:/etc/libvirt
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "1m"
