version: '3'

services:
  core:
    image: registry.rsdecsapps.net/demo/x11:1.2.5
    environment:
      - DISPLAY
      - VNC=true
    ipc: host
    network_mode: host
    pid: host
    privileged: true
    restart: always
    userns_mode: host
    volumes:
      - /dev:/dev:shared
      - /var/log:/var/log 
      - /var/run/:/var/run/ 
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "1m"
