version: '3'

services:
  core:
    image: brodintel/x11:1.5.0
    environment:
      - DISPLAY
      - VNC=true
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTPS_PROXY}
      - NO_PROXY=${NO_PROXY}
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - no_proxy=${no_proxy}
    ipc: host
    network_mode: host
    pid: host
    privileged: true
    restart: always
    userns_mode: host
    volumes:
      - /var/log:/var/log 
      - /run/:/run/
      - /tmp/:/tmp/
      - /lib/modules:/lib/modules
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "1m"
