version: '3'

services:
  core:
    image: brodintel/kind-core:v0.1
    environment:
      - UUID=
      - TOKEN=
    network_mode: host
    privileged: true
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "1m"
