version: '3'

volumes:
  kind_data:
    driver: local

services:
  core:
    image: brodintel/kind-core:v0.1
    environment:
      - UUID=${UUID}
      - TOKEN=${TOKEN}
    network_mode: host
    privileged: true
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - kind_data:/root
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "1m"
