version: "3.7"

services:
  winsrv2012:
    image: docker:19.03.12
    entrypoint: [sh, -c]
    environment:
      TASK_NAME: '{{.Task.Name}}'
    command: >-
      'exec docker run 
      --interactive
      --name winsrv2012
      --rm
      --privileged=true
      --net=host
      --dns=8.8.8.8 
      --dns=8.8.4.4 
      --env DISPLAY=":0"
      --env VNC=true
      --env RAM=4096 
      --env VIDEO=custom 
      --env CUSTOM_VIDEO="-display gtk,gl=on -vga qxl"
      --env GPU=""
      --env DISK_AHCI=false
      --label com.docker.stack.namespace=$$(docker container inspect --format "{{index .Config.Labels \"com.docker.stack.namespace\"}}" $${TASK_NAME})
      -v /run:/run
      -v /dev:/dev
      -v /tmp:/tmp
      registry.rsdecsapps.net/demo/winsrv2012:0.0.5'
    volumes:
      - /var/run:/var/run
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - node.platform.os == linux
          - engine.labels.graphics.i915 == true
          - engine.labels.vt_enabled == true
          # - engine.labels.serial_number == 8CC83219S9
          # - node.labels.gpu.available == true
