version: "3.7"

services:
  x11:
    image: docker:19.03.12
    entrypoint: [sh, -c]
    environment:
      TASK_NAME: '{{.Task.Name}}'
    command: >-
      'exec docker run -d
      --name zoom
      --rm
      --env DISPLAY=":0"
      --privileged=true
      --net=host
      --dns=8.8.8.8 
      --dns=8.8.4.4
      -v /var/log:/var/log 
      -v /run:/run 
      -v /dev:/dev:shared
      -v /tmp:/tmp
      --label com.docker.stack.namespace=$$(docker container inspect --format "{{index .Config.Labels \"com.docker.stack.namespace\"}}" $${TASK_NAME})
      registry.rsdecsapps.net/demo/zoom:0.0.1'
    volumes:
      - /var/run:/var/run
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - node.platform.os == linux
          # - engine.labels.graphics.i915 == true
          # - engine.labels.serial_number == 1905122097
          # - node.labels.gpu.available == true
          # - node.labels.usb.camera == true