version: '3'

services:
  core:
    image: linuxkit/getty:v0.8
    ipc: host
    network_mode: host
    pid: host
    privileged: true
    restart: always
    userns_mode: host
    volumes:
      - /hostroot:/hostroot
      - /hostroot/var/persist/etc/issue:/etc/motd
      - /etc/profile.d:/etc/profile.d
      - /hostroot/etc/getty.shadow:/etc/shadow
      - /hostroot/etc/sshd.passwd:/etc/passwd
      - /hostroot/etc/sshd.group:/etc/group
      - /etc/hostname:/etc/hostname
      - /home:/home
      - /run:/run
      - /tmp:/tmp
      - /hostroot/usr/bin/ctr:/usr/bin/ctr
      - /hostroot/usr/bin/runc:/usr/bin/runc
      - /hostroot/containers:/containers
      - /var/log:/var/log
      - /hostroot/var/log:/var/log/hostroot/
      - /hostroot/var/lib/containerd:/var/lib/containerd
      - /dev:/dev
      - /sys:/sys
    cap_add:
      - ALL
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "1m"
