version: "3.7"

services:
  chrome:
    image: registry.rsdecsapps.net/demo/chrome:0.0.1
    command: ['--no-sandbox', '--no-default-browser-check', '--no-crash-upload', 'https://www.youtube.com/watch?v=NP9zZqqXJpo&list=PLk2sjg_-F-MftRXx0mAnAKURajwQsAeNr']
    environment:
      DISPLAY: ":0"
    volumes:
      - /run:/run
      - /var/log:/var/log
      - /dev:/dev:shared
      - /tmp:/tmp
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - node.platform.os == linux
          - engine.labels.graphics.i915 == true
          # - engine.labels.serial_number == 8CC83219S9