version: "3.7"

services:
  x11:
    image: docker:19.03.0
    entrypoint: [sh, -c]
    environment:
      TASK_NAME: '{{.Task.Name}}'
    command: >-
      'exec docker run 
      --interactive
      --name x11
      --rm
      --env DISPLAY
      --env VNC=true
      --env AUTOSTART="pos=remote-viewer -f spice+unix://var/run/pos.sock"
      --privileged=true
      --net=host
      --label com.docker.stack.namespace=$$(docker container inspect --format "{{index .Config.Labels \"com.docker.stack.namespace\"}}" $${TASK_NAME})
      -v /dev:/dev:shared
      -v /var/log:/var/log 
      -v /var/run/:/var/run/ 
      -v /usr/bin/docker:/usr/bin/docker
      registry.edge.io/lab/x11:1.1.0'
    volumes:
      - /var/run:/var/run
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - node.platform.os == linux
          - engine.labels.graphics.i915 == true
          - engine.labels.serial_number == CZC7127XG8
          # - node.labels.gpu.available == true

  pos:
    image: docker:19.03.0
    entrypoint: [sh, -c]
    environment:
      TASK_NAME: '{{.Task.Name}}'
    command: >-
      'exec docker run 
      --interactive
      --name=pos 
      --net=host 
      --privileged=true 
      -v /dev:/dev:shared
      -v /var/run/:/var/run/ 
      --label com.docker.stack.namespace=$$(docker container inspect --format "{{index .Config.Labels \"com.docker.stack.namespace\"}}" $${TASK_NAME})
      registry.edge.io/lab/pos:0.0.1'
    volumes:
      - /var/run:/var/run
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - node.platform.os == linux
          - engine.labels.graphics.i915 == true
          - engine.labels.vt_enabled == true
          - engine.labels.serial_number == CZC7127XG8
