version: "3.7"

services:
  dos:
    image: docker:19.03.12
    entrypoint: [sh, -c]
    environment:
      TASK_NAME: '{{.Task.Name}}'
    command: >-
      'exec docker run 
      --interactive
      --name=dos 
      --net=host
      --dns=8.8.8.8 
      --dns=8.8.4.4  
      --privileged=true 
      --rm
      --env NETWORK=none
      --env VIDEO=custom 
      --env CUSTOM_VIDEO="-display gtk -vga cirrus"
      --env DISPLAY=":0"
      --env AUDIO=none
      --env ADD_FLAGS="-soundhw sb16,adlib,pcspk -audiodev pa,id=sound0,server=unix:/tmp/pulse-sock -rtc base=localtime "
      -v /run:/run
      -v /dev:/dev
      -v /tmp:/tmp
      --label com.docker.stack.namespace=$$(docker container inspect --format "{{index .Config.Labels \"com.docker.stack.namespace\"}}" $${TASK_NAME})
      brodintel/dos:0.0.5'
    volumes:
      - /var/run:/var/run
      - /tmp:/tmp
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - node.platform.os == linux
          # - engine.labels.graphics.i915 == true
          # - engine.labels.vt_enabled == true
          # - engine.labels.serial_number == 8CC83219S9
