---

# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: BSD-3-Clause

version: '3'

services:
  deploy:
    image: brodintel/esp-deploy:v1.0
    environment:
      - username=${username}
      - password=${password}
      - epassword=${epassword}
      - edge_key=${edge_key}
      - kernel_presets=${kernel_presets}
    ipc: host
    network_mode: host
    pid: host
    privileged: true
    restart: "no"
    userns_mode: host
    volumes:
      - /dev:/dev:shared
      - /:/host