---

# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: BSD-3-Clause

version: '3'

services:
  deploy:
    image: alpine
    environment:
      - FW_IMAGE=${kernel_image}
      - REBOOT=${reboot}
    ipc: host
    network_mode: host
    pid: host
    privileged: true
    restart: "no"
    userns_mode: host
    volumes:
      - /dev:/dev:shared
      - /:/host